//
// Created by Rishil Patel on 19/02/2020.
//

#ifndef LANGPROC_2019_CW_JETSTREAM_IDENTIFIER_HPP
#define LANGPROC_2019_CW_JETSTREAM_IDENTIFIER_HPP


class identifier {

};


#endif //LANGPROC_2019_CW_JETSTREAM_IDENTIFIER_HPP
